// src/utils/codeExtractor.js

/**
 * Extracts the first code block from a string.
 * It looks for blocks fenced with ```.
 * @param {string} text The text generated by the LLM.
 * @returns {string} The extracted code, or the original text if no block is found.
 */
function extractCode(text) {
  const codeBlockRegex = /```(?:\w+\n)?([\s\S]+?)```/;
  const match = text.match(codeBlockRegex);
  return match ? match[1].trim() : text.trim();
}

module.exports = { extractCode };